/*
 * To change this template  = new Segmento(), choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import base.ExpressaoRegular;
import convenio.Convenio;
import convenio.ConvenioErro;
import fachada.Fachada;
import java.util.Iterator;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JFrame;
import laudo.Eco;
import laudo.LaudoErro;
import laudoEscore.LaudoEscore;
import laudoEscore.LaudoEscoreErro;
import medico.Medico;
import medico.MedicoErro;
import paciente.Paciente;
import segmento.Segmento;

/**
 *
 * @author arlindo
 */
public class cadastroEscore_old extends javax.swing.JFrame {

    /**
     * Creates new form cadastroEscore
     */
    int laudoEcoId;
    
    public cadastroEscore_old(int laudoEcoId) {
        this.setAlwaysOnTop(true);
        initComponents();
        this.laudoEcoId = laudoEcoId;
         this.setAlwaysOnTop(false);
          setExtendedState(MAXIMIZED_BOTH);
    }

    public cadastroEscore_old(int laudoEcoId,Paciente p,Medico m,Convenio c,JFrame pai) {
        this.setAlwaysOnTop(true);
        initComponents();
        this.p = p;
        this.c = c;
        this.m = m;
        jLabel_nome_paciente.setText(p.getNome());
        jTextField_crm.setText(m.getCRM()+"");
        jTextField_nome.setText(m.getNome());
        this.laudoEcoId = laudoEcoId;
        this.setAlwaysOnTop(false);
        jRadioButton_esc.setSelected(true);
        setExtendedState(MAXIMIZED_BOTH); 
        try {
            atualizarCombo();
        } catch (ConvenioErro ex) {
            Logger.getLogger(cadastroEscore_old.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
     public void atualizarCombo() throws ConvenioErro{
        
        this.setAlwaysOnTop(false);
         
         Fachada f = new Fachada();
         List listar = f.pesquisarConvenioPorStatus();
         Iterator it = listar.iterator();
         while(it.hasNext()){
             Convenio c = (Convenio)it.next();             
             jComboBox_convenio.addItem(c.getNome()); 
             if(this.c != null){
                if(this.c.getNome().equals(c.getNome())){
                       jComboBox_convenio.setSelectedItem(c.getNome());
                       
                }
             }
         }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel_esquerda = new javax.swing.JPanel();
        jLabel_imagem_indice_escore = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jButton_Salvar = new javax.swing.JButton();
        jButton_voltar = new javax.swing.JButton();
        jPanel_direita = new javax.swing.JPanel();
        jLabel_segmento = new javax.swing.JLabel();
        jLabel_repouso = new javax.swing.JLabel();
        jLabel_baixa = new javax.swing.JLabel();
        jLabel_pico = new javax.swing.JLabel();
        jLabel_recuperacao = new javax.swing.JLabel();
        jLabel_segmento_1 = new javax.swing.JLabel();
        jLabel_segmento_2 = new javax.swing.JLabel();
        jLabel_segmento_3 = new javax.swing.JLabel();
        jLabel_segmento_4 = new javax.swing.JLabel();
        jLabel_segmento_5 = new javax.swing.JLabel();
        jLabel_segmento_6 = new javax.swing.JLabel();
        jLabel_segmento_7 = new javax.swing.JLabel();
        jLabel_segmento_8 = new javax.swing.JLabel();
        jLabel_segmento_9 = new javax.swing.JLabel();
        jLabel_segmento_10 = new javax.swing.JLabel();
        jLabel_segmento_11 = new javax.swing.JLabel();
        jLabel_segmento_12 = new javax.swing.JLabel();
        jLabel_segmento_13 = new javax.swing.JLabel();
        jLabel_segmento_14 = new javax.swing.JLabel();
        jLabel_segmento_15 = new javax.swing.JLabel();
        jLabel_segmento_17 = new javax.swing.JLabel();
        jLabel_segmento_16 = new javax.swing.JLabel();
        jTextField_repouso_1 = new javax.swing.JTextField();
        jTextField_baixa_dose_1 = new javax.swing.JTextField();
        jTextField_pico_1 = new javax.swing.JTextField();
        jTextField_recuperacao_1 = new javax.swing.JTextField();
        jTextField_repouso_2 = new javax.swing.JTextField();
        jTextField_baixa_dose_2 = new javax.swing.JTextField();
        jTextField_pico_2 = new javax.swing.JTextField();
        jTextField_recuperacao_2 = new javax.swing.JTextField();
        jTextField_repouso_3 = new javax.swing.JTextField();
        jTextField_baixa_dose_3 = new javax.swing.JTextField();
        jTextField_pico_3 = new javax.swing.JTextField();
        jTextField_recuperacao_3 = new javax.swing.JTextField();
        jTextField_repouso_4 = new javax.swing.JTextField();
        jTextField_baixa_dose_4 = new javax.swing.JTextField();
        jTextField_pico_4 = new javax.swing.JTextField();
        jTextField_recuperacao_4 = new javax.swing.JTextField();
        jTextField_repouso_5 = new javax.swing.JTextField();
        jTextField_baixa_dose_5 = new javax.swing.JTextField();
        jTextField_pico_5 = new javax.swing.JTextField();
        jTextField_recuperacao_5 = new javax.swing.JTextField();
        jTextField_repouso_6 = new javax.swing.JTextField();
        jTextField_baixa_dose_6 = new javax.swing.JTextField();
        jTextField_pico_6 = new javax.swing.JTextField();
        jTextField_recuperacao_6 = new javax.swing.JTextField();
        jTextField_repouso_7 = new javax.swing.JTextField();
        jTextField_baixa_dose_7 = new javax.swing.JTextField();
        jTextField_pico_7 = new javax.swing.JTextField();
        jTextField_recuperacao_7 = new javax.swing.JTextField();
        jTextField_repouso_8 = new javax.swing.JTextField();
        jTextField_baixa_dose_8 = new javax.swing.JTextField();
        jTextField_pico_8 = new javax.swing.JTextField();
        jTextField_recuperacao_8 = new javax.swing.JTextField();
        jTextField_repouso_9 = new javax.swing.JTextField();
        jTextField_baixa_dose_9 = new javax.swing.JTextField();
        jTextField_pico_9 = new javax.swing.JTextField();
        jTextField_recuperacao_9 = new javax.swing.JTextField();
        jTextField_repouso_10 = new javax.swing.JTextField();
        jTextField_baixa_dose_10 = new javax.swing.JTextField();
        jTextField_pico_10 = new javax.swing.JTextField();
        jTextField_recuperacao_10 = new javax.swing.JTextField();
        jTextField_repouso_11 = new javax.swing.JTextField();
        jTextField_baixa_dose_11 = new javax.swing.JTextField();
        jTextField_pico_11 = new javax.swing.JTextField();
        jTextField_recuperacao_11 = new javax.swing.JTextField();
        jTextField_repouso_12 = new javax.swing.JTextField();
        jTextField_baixa_dose_12 = new javax.swing.JTextField();
        jTextField_pico_12 = new javax.swing.JTextField();
        jTextField_recuperacao_12 = new javax.swing.JTextField();
        jTextField_repouso_13 = new javax.swing.JTextField();
        jTextField_baixa_dose_13 = new javax.swing.JTextField();
        jTextField_pico_13 = new javax.swing.JTextField();
        jTextField_recuperacao_13 = new javax.swing.JTextField();
        jTextField_repouso_14 = new javax.swing.JTextField();
        jTextField_baixa_dose_14 = new javax.swing.JTextField();
        jTextField_pico_14 = new javax.swing.JTextField();
        jTextField_recuperacao_14 = new javax.swing.JTextField();
        jTextField_repouso_15 = new javax.swing.JTextField();
        jTextField_baixa_dose_15 = new javax.swing.JTextField();
        jTextField_pico_15 = new javax.swing.JTextField();
        jTextField_recuperacao_15 = new javax.swing.JTextField();
        jTextField_repouso_16 = new javax.swing.JTextField();
        jTextField_baixa_dose_16 = new javax.swing.JTextField();
        jTextField_pico_16 = new javax.swing.JTextField();
        jTextField_recuperacao_16 = new javax.swing.JTextField();
        jTextField_recuperacao_17 = new javax.swing.JTextField();
        jTextField_pico_17 = new javax.swing.JTextField();
        jTextField_baixa_dose_17 = new javax.swing.JTextField();
        jTextField_repouso_17 = new javax.swing.JTextField();
        jTextField_crm = new javax.swing.JTextField();
        jTextField_nome = new javax.swing.JTextField();
        jLabel_medicoResp = new javax.swing.JLabel();
        jComboBox_convenio = new javax.swing.JComboBox();
        jLabel_Convenio = new javax.swing.JLabel();
        jLabel_paciente = new javax.swing.JLabel();
        jLabel_tipo = new javax.swing.JLabel();
        jButton_medicos = new javax.swing.JButton();
        jRadioButton_sub = new javax.swing.JRadioButton();
        jRadioButton_SEPD = new javax.swing.JRadioButton();
        jRadioButton_tt = new javax.swing.JRadioButton();
        jRadioButton_t = new javax.swing.JRadioButton();
        jRadioButton_SEPE1 = new javax.swing.JRadioButton();
        jLabel_nome_paciente = new javax.swing.JLabel();
        jRadioButton_esc = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);

        jLabel_imagem_indice_escore.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/indice_escore.png"))); // NOI18N

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("INDICE DE ESCORE DE CONTRATILIDADE");

        jButton_Salvar.setText("Salvar");
        jButton_Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SalvarActionPerformed(evt);
            }
        });

        jButton_voltar.setText("Voltar");
        jButton_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_voltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_esquerdaLayout = new javax.swing.GroupLayout(jPanel_esquerda);
        jPanel_esquerda.setLayout(jPanel_esquerdaLayout);
        jPanel_esquerdaLayout.setHorizontalGroup(
            jPanel_esquerdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_esquerdaLayout.createSequentialGroup()
                .addGroup(jPanel_esquerdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel_esquerdaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton_Salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel_imagem_indice_escore, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        jPanel_esquerdaLayout.setVerticalGroup(
            jPanel_esquerdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_esquerdaLayout.createSequentialGroup()
                .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_imagem_indice_escore, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_esquerdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Salvar)
                    .addComponent(jButton_voltar))
                .addGap(71, 71, 71))
        );

        jPanel_esquerda.setBounds(0, 480, 590, 600);
        jDesktopPane1.add(jPanel_esquerda, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel_segmento.setText("Segmento");

        jLabel_repouso.setText("Repouso");

        jLabel_baixa.setText("Baixa Dose");

        jLabel_pico.setText("Pico");

        jLabel_recuperacao.setText("Recuperação");

        jLabel_segmento_1.setText("1");

        jLabel_segmento_2.setText("2");

        jLabel_segmento_3.setText("3");

        jLabel_segmento_4.setText("4");

        jLabel_segmento_5.setText("5");

        jLabel_segmento_6.setText("6");

        jLabel_segmento_7.setText("7");

        jLabel_segmento_8.setText("8");

        jLabel_segmento_9.setText("9");

        jLabel_segmento_10.setText("10");

        jLabel_segmento_11.setText("11");

        jLabel_segmento_12.setText("12");

        jLabel_segmento_13.setText("13");

        jLabel_segmento_14.setText("14");

        jLabel_segmento_15.setText("15");

        jLabel_segmento_17.setText("17");

        jLabel_segmento_16.setText("16");

        javax.swing.GroupLayout jPanel_direitaLayout = new javax.swing.GroupLayout(jPanel_direita);
        jPanel_direita.setLayout(jPanel_direitaLayout);
        jPanel_direitaLayout.setHorizontalGroup(
            jPanel_direitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_direitaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_direitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_direitaLayout.createSequentialGroup()
                        .addGroup(jPanel_direitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_segmento_1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_segmento))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel_direitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_repouso, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_repouso_1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel_direitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_baixa_dose_2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel_direitaLayout.createSequentialGroup()
                                .addGroup(jPanel_direitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_baixa_dose_4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_baixa_dose_3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel_baixa)
                                    .addComponent(jTextField_baixa_dose_1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(1, 1, 1)))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel_direitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_direitaLayout.createSequentialGroup()
                                .addComponent(jLabel_pico, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel_recuperacao))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_direitaLayout.createSequentialGroup()
                                .addComponent(jTextField_pico_1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField_recuperacao_1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))
                    .addGroup(jPanel_direitaLayout.createSequentialGroup()
                        .addGroup(jPanel_direitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_direitaLayout.createSequentialGroup()
                                .addComponent(jLabel_segmento_17, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField_pico_17, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_recuperacao_17, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel_direitaLayout.createSequentialGroup()
                                .addGroup(jPanel_direitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel_direitaLayout.createSequentialGroup()
                                        .addComponent(jLabel_segmento_15, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextField_repouso_15, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel_direitaLayout.createSequentialGroup()
                                        .addComponent(jLabel_segmento_14, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextField_repouso_14, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel_direitaLayout.createSequentialGroup()
                                        .addComponent(jLabel_segmento_13, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextField_repouso_13, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel_direitaLayout.createSequentialGroup()
                                        .addComponent(jLabel_segmento_12, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextField_repouso_12, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel_direitaLayout.createSequentialGroup()
                                        .addComponent(jLabel_segmento_11, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextField_repouso_11, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel_direitaLayout.createSequentialGroup()
                                        .addComponent(jLabel_segmento_10, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextField_repouso_10, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel_direitaLayout.createSequentialGroup()
                                        .addComponent(jLabel_segmento_9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextField_repouso_9, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel_direitaLayout.createSequentialGroup()
                                        .addComponent(jLabel_segmento_8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextField_repouso_8, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel_direitaLayout.createSequentialGroup()
                                        .addComponent(jLabel_segmento_7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextField_repouso_7, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel_direitaLayout.createSequentialGroup()
                                        .addComponent(jLabel_segmento_6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextField_repouso_6, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel_direitaLayout.createSequentialGroup()
                                        .addComponent(jLabel_segmento_5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextField_repouso_5, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel_direitaLayout.createSequentialGroup()
                                        .addComponent(jLabel_segmento_4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextField_repouso_4, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel_direitaLayout.createSequentialGroup()
                                        .addComponent(jLabel_segmento_3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextField_repouso_3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel_direitaLayout.createSequentialGroup()
                                        .addComponent(jLabel_segmento_2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextField_repouso_2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel_direitaLayout.createSequentialGroup()
                                        .addComponent(jLabel_segmento_16, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(32, 32, 32)
                                        .addGroup(jPanel_direitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextField_repouso_17, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField_repouso_16, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(jPanel_direitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_direitaLayout.createSequentialGroup()
                                        .addGap(112, 112, 112)
                                        .addGroup(jPanel_direitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_direitaLayout.createSequentialGroup()
                                                .addComponent(jTextField_pico_2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextField_recuperacao_2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel_direitaLayout.createSequentialGroup()
                                                .addGroup(jPanel_direitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jTextField_pico_4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jTextField_pico_3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel_direitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jTextField_recuperacao_4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jTextField_recuperacao_3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addGroup(jPanel_direitaLayout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addGroup(jPanel_direitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel_direitaLayout.createSequentialGroup()
                                                .addGroup(jPanel_direitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jTextField_baixa_dose_15, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jTextField_baixa_dose_16, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jTextField_baixa_dose_17, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jTextField_baixa_dose_14, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jTextField_baixa_dose_13, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jTextField_baixa_dose_12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(15, 15, 15)
                                                .addGroup(jPanel_direitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jTextField_pico_12, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jTextField_pico_13, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jTextField_pico_14, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jTextField_pico_15, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jTextField_pico_16, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel_direitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jTextField_recuperacao_12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jTextField_recuperacao_13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jTextField_recuperacao_14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jTextField_recuperacao_15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jTextField_recuperacao_16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(jPanel_direitaLayout.createSequentialGroup()
                                                .addGroup(jPanel_direitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jTextField_baixa_dose_6, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jTextField_baixa_dose_5, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jTextField_baixa_dose_7, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(15, 15, 15)
                                                .addGroup(jPanel_direitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jTextField_pico_5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jTextField_pico_6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jTextField_pico_7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel_direitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jTextField_recuperacao_7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jTextField_recuperacao_5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jTextField_recuperacao_6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_direitaLayout.createSequentialGroup()
                                                .addGroup(jPanel_direitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jTextField_baixa_dose_11, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jTextField_baixa_dose_9, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jTextField_baixa_dose_8, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jTextField_baixa_dose_10, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(15, 15, 15)
                                                .addGroup(jPanel_direitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_direitaLayout.createSequentialGroup()
                                                        .addGap(2, 2, 2)
                                                        .addGroup(jPanel_direitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jTextField_recuperacao_9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_direitaLayout.createSequentialGroup()
                                                                .addComponent(jTextField_pico_10, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(jTextField_recuperacao_10, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                            .addComponent(jTextField_pico_9, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_direitaLayout.createSequentialGroup()
                                                                .addComponent(jTextField_pico_8, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(jTextField_recuperacao_8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_direitaLayout.createSequentialGroup()
                                                        .addComponent(jTextField_pico_11, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jTextField_recuperacao_11, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))))))))
                        .addContainerGap())))
        );
        jPanel_direitaLayout.setVerticalGroup(
            jPanel_direitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_direitaLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel_direitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_segmento)
                    .addComponent(jLabel_repouso)
                    .addComponent(jLabel_baixa)
                    .addComponent(jLabel_pico)
                    .addComponent(jLabel_recuperacao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_direitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_segmento_1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_repouso_1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jTextField_baixa_dose_1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jTextField_recuperacao_1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jTextField_pico_1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_direitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_segmento_2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_repouso_2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jTextField_baixa_dose_2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jTextField_recuperacao_2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jTextField_pico_2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_direitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_segmento_3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_repouso_3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jTextField_baixa_dose_3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jTextField_recuperacao_3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jTextField_pico_3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_direitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_segmento_4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_repouso_4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jTextField_baixa_dose_4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jTextField_recuperacao_4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jTextField_pico_4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_direitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_segmento_5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_repouso_5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jTextField_baixa_dose_5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jTextField_recuperacao_5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jTextField_pico_5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_direitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_segmento_6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_repouso_6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jTextField_baixa_dose_6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jTextField_recuperacao_6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jTextField_pico_6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_direitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_segmento_7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_repouso_7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jTextField_baixa_dose_7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jTextField_recuperacao_7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jTextField_pico_7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_direitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_segmento_8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_repouso_8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jTextField_baixa_dose_8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jTextField_recuperacao_8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jTextField_pico_8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_direitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_segmento_9, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_repouso_9, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jTextField_baixa_dose_9, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jTextField_recuperacao_9, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jTextField_pico_9, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_direitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_segmento_10, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_repouso_10, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jTextField_baixa_dose_10, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jTextField_recuperacao_10, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jTextField_pico_10, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_direitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_segmento_11, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_repouso_11, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jTextField_baixa_dose_11, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jTextField_recuperacao_11, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jTextField_pico_11, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_direitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_segmento_12, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_repouso_12, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jTextField_baixa_dose_12, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jTextField_recuperacao_12, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jTextField_pico_12, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_direitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_segmento_13, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_repouso_13, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jTextField_baixa_dose_13, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jTextField_recuperacao_13, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jTextField_pico_13, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_direitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_segmento_14, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_repouso_14, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jTextField_baixa_dose_14, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jTextField_recuperacao_14, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jTextField_pico_14, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_direitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_segmento_15, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_repouso_15, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jTextField_baixa_dose_15, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jTextField_recuperacao_15, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jTextField_pico_15, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_direitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_segmento_16, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_repouso_16, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jTextField_baixa_dose_16, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jTextField_recuperacao_16, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jTextField_pico_16, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_direitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_repouso_17, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jTextField_baixa_dose_17, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jTextField_recuperacao_17, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jTextField_pico_17, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel_segmento_17, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel_direita.setBounds(640, 460, 480, 600);
        jDesktopPane1.add(jPanel_direita, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTextField_crm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_crmActionPerformed(evt);
            }
        });
        jTextField_crm.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_crmFocusLost(evt);
            }
        });

        jLabel_medicoResp.setText("Médico Responsável:");

        jComboBox_convenio.setModel(new javax.swing.DefaultComboBoxModel(new String[] { ".: Selecione :." }));

        jLabel_Convenio.setText("Convênio");

        jLabel_paciente.setText("Paciente");

        jLabel_tipo.setText("Tipos de laudos:");

        jButton_medicos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/busca.png"))); // NOI18N
        jButton_medicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_medicosActionPerformed(evt);
            }
        });

        jRadioButton_sub.setBackground(new java.awt.Color(254, 254, 254));
        jRadioButton_sub.setText("Subjetivo");
        jRadioButton_sub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_subActionPerformed(evt);
            }
        });

        jRadioButton_SEPD.setBackground(new java.awt.Color(254, 254, 254));
        jRadioButton_SEPD.setText("Sob estresse pela Dobutamina");
        jRadioButton_SEPD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_SEPDActionPerformed(evt);
            }
        });

        jRadioButton_tt.setBackground(new java.awt.Color(254, 254, 254));
        jRadioButton_tt.setText("Transtorácico e Transesofágico");
        jRadioButton_tt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_ttActionPerformed(evt);
            }
        });

        jRadioButton_t.setBackground(new java.awt.Color(254, 254, 254));
        jRadioButton_t.setText("Transtorácico");
        jRadioButton_t.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_tActionPerformed(evt);
            }
        });

        jRadioButton_SEPE1.setBackground(new java.awt.Color(254, 254, 254));
        jRadioButton_SEPE1.setText("Sob estresse pelo Esforço");
        jRadioButton_SEPE1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_SEPE1ActionPerformed(evt);
            }
        });

        jRadioButton_esc.setBackground(new java.awt.Color(254, 254, 254));
        jRadioButton_esc.setText("Escore");
        jRadioButton_esc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_escActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1341, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_paciente, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_Convenio))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox_convenio, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_nome_paciente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel_medicoResp, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_crm, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_medicos, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton_tt)
                    .addComponent(jRadioButton_SEPD, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton_sub, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton_esc, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton_SEPE1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton_t, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_medicos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel_paciente, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel_nome_paciente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(4, 4, 4)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_Convenio, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox_convenio, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_medicoResp, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_crm, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_tipo)
                            .addComponent(jRadioButton_tt)
                            .addComponent(jRadioButton_t))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton_SEPD)
                            .addComponent(jRadioButton_SEPE1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton_sub)
                            .addComponent(jRadioButton_esc))))
                .addGap(18, 18, 18)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_voltarActionPerformed
        this.dispose();
        try {
            new exibirLaudoEscore(laudoEcoId).setVisible(true);
        } catch (LaudoEscoreErro ex) {
            Logger.getLogger(cadastroEscore_old.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_voltarActionPerformed

    private void jButton_SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SalvarActionPerformed
        this.setAlwaysOnTop(false);
        
        Segmento segmento1  = new Segmento(), segmento2 = new Segmento(), segmento3  = new Segmento(),segmento4  = new Segmento(),segmento5  = new Segmento(),segmento6  = new Segmento(),segmento7  = new Segmento(),segmento8  = new Segmento(),segmento9  = new Segmento(),segmento10  = new Segmento(), segmento11  = new Segmento(),segmento12  = new Segmento(),segmento13  = new Segmento(),segmento14  = new Segmento(),segmento15  = new Segmento(),segmento16  = new Segmento(),segmento17 = new Segmento();
        
        segmento1.setBaixaDose((jTextField_baixa_dose_1.getText().isEmpty()) ? 0 : Double.parseDouble(jTextField_baixa_dose_1.getText()));
        segmento1.setPico((jTextField_pico_1.getText().isEmpty()) ? 0 : Double.parseDouble(jTextField_pico_1.getText()));
        segmento1.setRecuperacao((jTextField_recuperacao_1.getText().isEmpty()) ? 0 : Double.parseDouble(jTextField_recuperacao_1.getText()));
        segmento1.setRepouso((jTextField_repouso_1.getText().isEmpty()) ? 0 : Double.parseDouble(jTextField_repouso_1.getText()));
        
        segmento2.setBaixaDose((jTextField_baixa_dose_2.getText().isEmpty()) ? 0 : Double.parseDouble(jTextField_baixa_dose_2.getText()));
        segmento2.setPico((jTextField_pico_2.getText().isEmpty()) ? 0 : Double.parseDouble(jTextField_pico_2.getText()));
        segmento2.setRecuperacao((jTextField_recuperacao_2.getText().isEmpty()) ? 0 : Double.parseDouble(jTextField_recuperacao_2.getText()));
        segmento2.setRepouso((jTextField_repouso_2.getText().isEmpty()) ? 0 : Double.parseDouble(jTextField_repouso_2.getText()));
        
        segmento3.setBaixaDose((jTextField_baixa_dose_3.getText().isEmpty()) ? 0 : Double.parseDouble(jTextField_baixa_dose_3.getText()));
        segmento3.setPico((jTextField_pico_3.getText().isEmpty()) ? 0 : Double.parseDouble(jTextField_pico_3.getText()));
        segmento3.setRecuperacao((jTextField_recuperacao_3.getText().isEmpty()) ? 0 : Double.parseDouble(jTextField_recuperacao_3.getText()));
        segmento3.setRepouso((jTextField_repouso_3.getText().isEmpty()) ? 0 : Double.parseDouble(jTextField_repouso_3.getText()));
        
        segmento4.setBaixaDose((jTextField_baixa_dose_4.getText().isEmpty()) ? 0 : Double.parseDouble(jTextField_baixa_dose_4.getText()));
        segmento4.setPico((jTextField_pico_4.getText().isEmpty()) ? 0 : Double.parseDouble(jTextField_pico_4.getText()));
        segmento4.setRecuperacao((jTextField_recuperacao_4.getText().isEmpty()) ? 0 : Double.parseDouble(jTextField_recuperacao_4.getText()));
        segmento4.setRepouso((jTextField_repouso_4.getText().isEmpty()) ? 0 : Double.parseDouble(jTextField_repouso_4.getText()));
        
        segmento5.setBaixaDose((jTextField_baixa_dose_5.getText().isEmpty()) ? 0 : Double.parseDouble(jTextField_baixa_dose_5.getText()));
        segmento5.setPico((jTextField_pico_5.getText().isEmpty()) ? 0 : Double.parseDouble(jTextField_pico_5.getText()));
        segmento5.setRecuperacao((jTextField_recuperacao_5.getText().isEmpty()) ? 0 : Double.parseDouble(jTextField_recuperacao_5.getText()));
        segmento5.setRepouso((jTextField_repouso_5.getText().isEmpty()) ? 0 : Double.parseDouble(jTextField_repouso_5.getText()));
        
        segmento6.setBaixaDose((jTextField_baixa_dose_6.getText().isEmpty()) ? 0 : Double.parseDouble(jTextField_baixa_dose_6.getText()));
        segmento6.setPico((jTextField_pico_6.getText().isEmpty()) ? 0 : Double.parseDouble(jTextField_pico_6.getText()));
        segmento6.setRecuperacao((jTextField_recuperacao_6.getText().isEmpty()) ? 0 : Double.parseDouble(jTextField_recuperacao_6.getText()));
        segmento6.setRepouso((jTextField_repouso_6.getText().isEmpty()) ? 0 : Double.parseDouble(jTextField_repouso_6.getText()));
        
        segmento7.setBaixaDose((jTextField_baixa_dose_7.getText().isEmpty()) ? 0 : Double.parseDouble(jTextField_baixa_dose_7.getText()));
        segmento7.setPico((jTextField_pico_7.getText().isEmpty()) ? 0 : Double.parseDouble(jTextField_pico_7.getText()));
        segmento7.setRecuperacao((jTextField_recuperacao_7.getText().isEmpty()) ? 0 : Double.parseDouble(jTextField_recuperacao_7.getText()));
        segmento7.setRepouso((jTextField_repouso_7.getText().isEmpty()) ? 0 : Double.parseDouble(jTextField_repouso_7.getText()));
        
        segmento8.setBaixaDose((jTextField_baixa_dose_8.getText().isEmpty()) ? 0 : Double.parseDouble(jTextField_baixa_dose_8.getText()));
        segmento8.setPico((jTextField_pico_8.getText().isEmpty()) ? 0 : Double.parseDouble(jTextField_pico_8.getText()));
        segmento8.setRecuperacao((jTextField_recuperacao_8.getText().isEmpty()) ? 0 : Double.parseDouble(jTextField_recuperacao_8.getText()));
        segmento8.setRepouso((jTextField_repouso_8.getText().isEmpty()) ? 0 : Double.parseDouble(jTextField_repouso_8.getText()));
        
        segmento9.setBaixaDose((jTextField_baixa_dose_9.getText().isEmpty()) ? 0 : Double.parseDouble(jTextField_baixa_dose_9.getText()));
        segmento9.setPico((jTextField_pico_9.getText().isEmpty()) ? 0 : Double.parseDouble(jTextField_pico_9.getText()));
        segmento9.setRecuperacao((jTextField_recuperacao_9.getText().isEmpty()) ? 0 : Double.parseDouble(jTextField_recuperacao_9.getText()));
        segmento9.setRepouso((jTextField_repouso_9.getText().isEmpty()) ? 0 : Double.parseDouble(jTextField_repouso_9.getText()));
        
        segmento10.setBaixaDose((jTextField_baixa_dose_10.getText().isEmpty()) ? 0 : Double.parseDouble(jTextField_baixa_dose_10.getText()));
        segmento10.setPico((jTextField_pico_10.getText().isEmpty()) ? 0 : Double.parseDouble(jTextField_pico_10.getText()));
        segmento10.setRecuperacao((jTextField_recuperacao_10.getText().isEmpty()) ? 0 : Double.parseDouble(jTextField_recuperacao_10.getText()));
        segmento10.setRepouso((jTextField_repouso_10.getText().isEmpty()) ? 0 : Double.parseDouble(jTextField_repouso_10.getText()));
        
        segmento11.setBaixaDose((jTextField_baixa_dose_11.getText().isEmpty()) ? 0 : Double.parseDouble(jTextField_baixa_dose_11.getText()));
        segmento11.setPico((jTextField_pico_11.getText().isEmpty()) ? 0 : Double.parseDouble(jTextField_pico_11.getText()));
        segmento11.setRecuperacao((jTextField_recuperacao_11.getText().isEmpty()) ? 0 : Double.parseDouble(jTextField_recuperacao_11.getText()));
        segmento11.setRepouso((jTextField_repouso_11.getText().isEmpty()) ? 0 : Double.parseDouble(jTextField_repouso_11.getText()));
        
        segmento12.setBaixaDose((jTextField_baixa_dose_12.getText().isEmpty()) ? 0 : Double.parseDouble(jTextField_baixa_dose_12.getText()));
        segmento12.setPico((jTextField_pico_12.getText().isEmpty()) ? 0 : Double.parseDouble(jTextField_pico_12.getText()));
        segmento12.setRecuperacao((jTextField_recuperacao_12.getText().isEmpty()) ? 0 : Double.parseDouble(jTextField_recuperacao_12.getText()));
        segmento12.setRepouso((jTextField_repouso_12.getText().isEmpty()) ? 0 : Double.parseDouble(jTextField_repouso_12.getText()));
        
        segmento13.setBaixaDose((jTextField_baixa_dose_13.getText().isEmpty()) ? 0 : Double.parseDouble(jTextField_baixa_dose_13.getText()));
        segmento13.setPico((jTextField_pico_13.getText().isEmpty()) ? 0 : Double.parseDouble(jTextField_pico_13.getText()));
        segmento13.setRecuperacao((jTextField_recuperacao_13.getText().isEmpty()) ? 0 : Double.parseDouble(jTextField_recuperacao_13.getText()));
        segmento13.setRepouso((jTextField_repouso_13.getText().isEmpty()) ? 0 : Double.parseDouble(jTextField_repouso_13.getText()));
        
        segmento14.setBaixaDose((jTextField_baixa_dose_14.getText().isEmpty()) ? 0 : Double.parseDouble(jTextField_baixa_dose_14.getText()));
        segmento14.setPico((jTextField_pico_14.getText().isEmpty()) ? 0 : Double.parseDouble(jTextField_pico_14.getText()));
        segmento14.setRecuperacao((jTextField_recuperacao_14.getText().isEmpty()) ? 0 : Double.parseDouble(jTextField_recuperacao_14.getText()));
        segmento14.setRepouso((jTextField_repouso_14.getText().isEmpty()) ? 0 : Double.parseDouble(jTextField_repouso_14.getText()));
        
        segmento15.setBaixaDose((jTextField_baixa_dose_15.getText().isEmpty()) ? 0 : Double.parseDouble(jTextField_baixa_dose_15.getText()));
        segmento15.setPico((jTextField_pico_15.getText().isEmpty()) ? 0 : Double.parseDouble(jTextField_pico_15.getText()));
        segmento15.setRecuperacao((jTextField_recuperacao_15.getText().isEmpty()) ? 0 : Double.parseDouble(jTextField_recuperacao_15.getText()));
        segmento15.setRepouso((jTextField_repouso_15.getText().isEmpty()) ? 0 : Double.parseDouble(jTextField_repouso_15.getText()));
        
        segmento16.setBaixaDose((jTextField_baixa_dose_16.getText().isEmpty()) ? 0 : Double.parseDouble(jTextField_baixa_dose_16.getText()));
        segmento16.setPico((jTextField_pico_16.getText().isEmpty()) ? 0 : Double.parseDouble(jTextField_pico_16.getText()));
        segmento16.setRecuperacao((jTextField_recuperacao_16.getText().isEmpty()) ? 0 : Double.parseDouble(jTextField_recuperacao_16.getText()));
        segmento16.setRepouso((jTextField_repouso_16.getText().isEmpty()) ? 0 : Double.parseDouble(jTextField_repouso_16.getText()));
        
        segmento17.setBaixaDose((jTextField_baixa_dose_17.getText().isEmpty()) ? 0 : Double.parseDouble(jTextField_baixa_dose_17.getText()));
        segmento17.setPico((jTextField_pico_17.getText().isEmpty()) ? 0 : Double.parseDouble(jTextField_pico_17.getText()));
        segmento17.setRecuperacao((jTextField_recuperacao_17.getText().isEmpty()) ? 0 : Double.parseDouble(jTextField_recuperacao_17.getText()));
        segmento17.setRepouso((jTextField_repouso_17.getText().isEmpty()) ? 0 : Double.parseDouble(jTextField_repouso_17.getText())); 
        
        LaudoEscore escore = new LaudoEscore(laudoEcoId,segmento1, segmento2, segmento3, segmento4, segmento5, segmento6, segmento7, segmento8, segmento9, segmento10, segmento11, segmento12, segmento13, segmento14, segmento15, segmento16, segmento17);
        Fachada f = new Fachada();
        try {
            f.cadastrarLaudoEscore(escore);
        } catch (LaudoEscoreErro ex) {
            Logger.getLogger(cadastroEscore_old.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton_SalvarActionPerformed

    private void jTextField_crmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_crmActionPerformed
        String crm = jTextField_crm.getText();
        ExpressaoRegular er = new ExpressaoRegular();
        if(er.isNum(crm)){
            Fachada f = new Fachada();
            this.setAlwaysOnTop(false);
            try {
                m = f.pesquisarMedicoPorCrm(Integer.parseInt(jTextField_crm.getText()));
                jTextField_nome.setText(m.getNome());

            } catch (MedicoErro ex) {

                Logger.getLogger(cadastroSubjetivo.class.getName()).log(Level.SEVERE, null, ex);

            }
        }else{
            jTextField_crm.setText("");
        }
    }//GEN-LAST:event_jTextField_crmActionPerformed

    private void jButton_medicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_medicosActionPerformed
        // TODO add your handling code here:
        JDialog dialogo = new selecionaMedicoDial(this,true);
        dialogo.setVisible(true);
        Fachada f = new Fachada();
        try {
            
            this.setEnabled(true);
            Medico m = null;
            m = f.pesquisarMedicoAux();
            jTextField_nome.setText(m.getNome());
            jTextField_crm.setText(m.getCRM()+"");
                if(m!=null)
                    this.m = m;
            f.excluirMedicoAux(m);
        } catch (MedicoErro ex) {
            Logger.getLogger(cadastroLaudo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_medicosActionPerformed

    private void jRadioButton_subActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_subActionPerformed
        // TODO add your handling code here:
        Fachada f = new Fachada();
        try {
            f.excluirLaudoUltimoId();
            new cadastroSubjetivo(p, m, c, this).setVisible(true);
            this.dispose();
        } catch (LaudoErro ex) {
            Logger.getLogger(cadastroEcoEstresse.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jRadioButton_subActionPerformed

    private void jRadioButton_SEPDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_SEPDActionPerformed
        // TODO add your handling code here:
        Fachada f = new Fachada();
        try {
            f.excluirLaudoUltimoId();
        } catch (LaudoErro ex) {
            Logger.getLogger(cadastroEcoEstresse.class.getName()).log(Level.SEVERE, null, ex);
        }

        tipo = "SEPD";
        eco.setTipo(tipo);
        jRadioButton_SEPE1.setSelected(false);
        try {
            f.cadastrarLaudoSub(eco);
        } catch (LaudoErro ex) {
            Logger.getLogger(cadastroEcoEstresse.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jRadioButton_SEPDActionPerformed

    private void jRadioButton_ttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_ttActionPerformed
        // TODO add your handling code here:
        Fachada f = new Fachada();
        try {
            f.excluirLaudoUltimoId();
            new cadastroLaudo(p,m,c,true, this).setVisible(true);
            this.setVisible(false);
        } catch (LaudoErro ex) {
            Logger.getLogger(cadastroEcoEstresse.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jRadioButton_ttActionPerformed

    private void jRadioButton_tActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_tActionPerformed
        // TODO add your handling code here:
        Fachada f = new Fachada();
        try {
            f.excluirLaudoUltimoId();
            new cadastroLaudo(p,m,c,false, this).setVisible(true);
            this.dispose();
        } catch (LaudoErro ex) {
            Logger.getLogger(cadastroEcoEstresse.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jRadioButton_tActionPerformed

    private void jRadioButton_SEPE1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_SEPE1ActionPerformed
        // TODO add your handling code here:
        Fachada f = new Fachada();
        try {
            f.excluirLaudoUltimoId();
        } catch (LaudoErro ex) {
            Logger.getLogger(cadastroEcoEstresse.class.getName()).log(Level.SEVERE, null, ex);
        }

        tipo = "SEPE";
        eco.setTipo(tipo);
        try {
            f.cadastrarLaudoSub(eco);
        } catch (LaudoErro ex) {
            Logger.getLogger(cadastroEcoEstresse.class.getName()).log(Level.SEVERE, null, ex);
        }

        jRadioButton_SEPD.setSelected(false);
    }//GEN-LAST:event_jRadioButton_SEPE1ActionPerformed

    private void jRadioButton_escActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_escActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton_escActionPerformed

    private void jTextField_crmFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_crmFocusLost
        String crm = jTextField_crm.getText();
        ExpressaoRegular er = new ExpressaoRegular();
        if(er.isNum(crm)){
            Fachada f = new Fachada();
            this.setAlwaysOnTop(false);
            try {
                m = f.pesquisarMedicoPorCrm(Integer.parseInt(jTextField_crm.getText()));
                jTextField_nome.setText(m.getNome());

            } catch (MedicoErro ex) {

                Logger.getLogger(cadastroSubjetivo.class.getName()).log(Level.SEVERE, null, ex);

            }
        }else{
            jTextField_crm.setText("");
        }
    }//GEN-LAST:event_jTextField_crmFocusLost

    
    String tipo;
    Eco eco;
    Medico m;
    Paciente p;
    Convenio c;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Salvar;
    private javax.swing.JButton jButton_medicos;
    private javax.swing.JButton jButton_voltar;
    private javax.swing.JComboBox jComboBox_convenio;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel_Convenio;
    private javax.swing.JLabel jLabel_baixa;
    private javax.swing.JLabel jLabel_imagem_indice_escore;
    private javax.swing.JLabel jLabel_medicoResp;
    private javax.swing.JLabel jLabel_nome_paciente;
    private javax.swing.JLabel jLabel_paciente;
    private javax.swing.JLabel jLabel_pico;
    private javax.swing.JLabel jLabel_recuperacao;
    private javax.swing.JLabel jLabel_repouso;
    private javax.swing.JLabel jLabel_segmento;
    private javax.swing.JLabel jLabel_segmento_1;
    private javax.swing.JLabel jLabel_segmento_10;
    private javax.swing.JLabel jLabel_segmento_11;
    private javax.swing.JLabel jLabel_segmento_12;
    private javax.swing.JLabel jLabel_segmento_13;
    private javax.swing.JLabel jLabel_segmento_14;
    private javax.swing.JLabel jLabel_segmento_15;
    private javax.swing.JLabel jLabel_segmento_16;
    private javax.swing.JLabel jLabel_segmento_17;
    private javax.swing.JLabel jLabel_segmento_2;
    private javax.swing.JLabel jLabel_segmento_3;
    private javax.swing.JLabel jLabel_segmento_4;
    private javax.swing.JLabel jLabel_segmento_5;
    private javax.swing.JLabel jLabel_segmento_6;
    private javax.swing.JLabel jLabel_segmento_7;
    private javax.swing.JLabel jLabel_segmento_8;
    private javax.swing.JLabel jLabel_segmento_9;
    private javax.swing.JLabel jLabel_tipo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel_direita;
    private javax.swing.JPanel jPanel_esquerda;
    private javax.swing.JRadioButton jRadioButton_SEPD;
    private javax.swing.JRadioButton jRadioButton_SEPE1;
    private javax.swing.JRadioButton jRadioButton_esc;
    private javax.swing.JRadioButton jRadioButton_sub;
    private javax.swing.JRadioButton jRadioButton_t;
    private javax.swing.JRadioButton jRadioButton_tt;
    private javax.swing.JTextField jTextField_baixa_dose_1;
    private javax.swing.JTextField jTextField_baixa_dose_10;
    private javax.swing.JTextField jTextField_baixa_dose_11;
    private javax.swing.JTextField jTextField_baixa_dose_12;
    private javax.swing.JTextField jTextField_baixa_dose_13;
    private javax.swing.JTextField jTextField_baixa_dose_14;
    private javax.swing.JTextField jTextField_baixa_dose_15;
    private javax.swing.JTextField jTextField_baixa_dose_16;
    private javax.swing.JTextField jTextField_baixa_dose_17;
    private javax.swing.JTextField jTextField_baixa_dose_2;
    private javax.swing.JTextField jTextField_baixa_dose_3;
    private javax.swing.JTextField jTextField_baixa_dose_4;
    private javax.swing.JTextField jTextField_baixa_dose_5;
    private javax.swing.JTextField jTextField_baixa_dose_6;
    private javax.swing.JTextField jTextField_baixa_dose_7;
    private javax.swing.JTextField jTextField_baixa_dose_8;
    private javax.swing.JTextField jTextField_baixa_dose_9;
    private javax.swing.JTextField jTextField_crm;
    private javax.swing.JTextField jTextField_nome;
    private javax.swing.JTextField jTextField_pico_1;
    private javax.swing.JTextField jTextField_pico_10;
    private javax.swing.JTextField jTextField_pico_11;
    private javax.swing.JTextField jTextField_pico_12;
    private javax.swing.JTextField jTextField_pico_13;
    private javax.swing.JTextField jTextField_pico_14;
    private javax.swing.JTextField jTextField_pico_15;
    private javax.swing.JTextField jTextField_pico_16;
    private javax.swing.JTextField jTextField_pico_17;
    private javax.swing.JTextField jTextField_pico_2;
    private javax.swing.JTextField jTextField_pico_3;
    private javax.swing.JTextField jTextField_pico_4;
    private javax.swing.JTextField jTextField_pico_5;
    private javax.swing.JTextField jTextField_pico_6;
    private javax.swing.JTextField jTextField_pico_7;
    private javax.swing.JTextField jTextField_pico_8;
    private javax.swing.JTextField jTextField_pico_9;
    private javax.swing.JTextField jTextField_recuperacao_1;
    private javax.swing.JTextField jTextField_recuperacao_10;
    private javax.swing.JTextField jTextField_recuperacao_11;
    private javax.swing.JTextField jTextField_recuperacao_12;
    private javax.swing.JTextField jTextField_recuperacao_13;
    private javax.swing.JTextField jTextField_recuperacao_14;
    private javax.swing.JTextField jTextField_recuperacao_15;
    private javax.swing.JTextField jTextField_recuperacao_16;
    private javax.swing.JTextField jTextField_recuperacao_17;
    private javax.swing.JTextField jTextField_recuperacao_2;
    private javax.swing.JTextField jTextField_recuperacao_3;
    private javax.swing.JTextField jTextField_recuperacao_4;
    private javax.swing.JTextField jTextField_recuperacao_5;
    private javax.swing.JTextField jTextField_recuperacao_6;
    private javax.swing.JTextField jTextField_recuperacao_7;
    private javax.swing.JTextField jTextField_recuperacao_8;
    private javax.swing.JTextField jTextField_recuperacao_9;
    private javax.swing.JTextField jTextField_repouso_1;
    private javax.swing.JTextField jTextField_repouso_10;
    private javax.swing.JTextField jTextField_repouso_11;
    private javax.swing.JTextField jTextField_repouso_12;
    private javax.swing.JTextField jTextField_repouso_13;
    private javax.swing.JTextField jTextField_repouso_14;
    private javax.swing.JTextField jTextField_repouso_15;
    private javax.swing.JTextField jTextField_repouso_16;
    private javax.swing.JTextField jTextField_repouso_17;
    private javax.swing.JTextField jTextField_repouso_2;
    private javax.swing.JTextField jTextField_repouso_3;
    private javax.swing.JTextField jTextField_repouso_4;
    private javax.swing.JTextField jTextField_repouso_5;
    private javax.swing.JTextField jTextField_repouso_6;
    private javax.swing.JTextField jTextField_repouso_7;
    private javax.swing.JTextField jTextField_repouso_8;
    private javax.swing.JTextField jTextField_repouso_9;
    // End of variables declaration//GEN-END:variables
}
