/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import base.Base;
import base.Data;
import base.ExpressaoRegular;
import fachada.Fachada;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.GregorianCalendar;
import java.util.InputMismatchException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;
import paciente.Paciente;
import paciente.PacienteErro;

/**
 *
 * 
 */
public class editaCadastroPaciente extends javax.swing.JFrame {

    /**
     * Creates new form cadastroPaciente
     */
    MaskFormatter formatoDataNascimento, formatotelefone, formatocpf;
    public editaCadastroPaciente(Paciente p) {
        
        this.setAlwaysOnTop(false);
        
        Dimension d = new Dimension (  
            (int) Toolkit.getDefaultToolkit ().getScreenSize ().getWidth (),(int) Toolkit.getDefaultToolkit().getScreenSize().getHeight());  

        this.setSize(d);
        this.setPreferredSize(d);
        this.setMinimumSize(d);
        
        initComponents();
        this.p = p;
        jTextField_nome.setText(p.getNome());
        jFormattedTextField_cpf.setText(p.getCpf());
        jFormattedTextField_dt_nascimento.setText(p.getDataNasc());
        jFormattedTextField_telefone.setText(p.getTel());
        if(p.getSexo().equals("Masculino")) {
            jComboBox_sexo.setSelectedIndex(1);
        }
        else {
            jComboBox_sexo.setSelectedIndex(0);
        }
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPaneGeral = new javax.swing.JDesktopPane();
        jLabel_topo = new javax.swing.JLabel();
        jLabel_nome = new javax.swing.JLabel();
        jTextField_nome = new javax.swing.JTextField();
        jLabel_dt_nascimento = new javax.swing.JLabel();
        try{
            formatoDataNascimento = new MaskFormatter("##/##/####");
        }catch(Exception erro){
            JOptionPane.showMessageDialog(null,"Erro ao inserir a Data de Nascimento");
        }
        jFormattedTextField_dt_nascimento = new JFormattedTextField(formatoDataNascimento);
        jLabel_cpf = new javax.swing.JLabel();
        try{
            formatocpf = new MaskFormatter("###.###.###-##");
        }catch(Exception erro){
            JOptionPane.showMessageDialog(null,"Erro ao inserir o CPF");
        }
        jFormattedTextField_cpf = new JFormattedTextField(formatocpf); ;
        jLabel_sexo = new javax.swing.JLabel();
        jComboBox_sexo = new javax.swing.JComboBox();
        jLabel_telefone = new javax.swing.JLabel();
        try{      formatotelefone = new MaskFormatter("(##)####-####");   }catch(Exception erro){       JOptionPane.showMessageDialog(null,"Erro ao inserir o Telefone");   }
        jFormattedTextField_telefone = new JFormattedTextField(formatotelefone);
        jButton_atualizar = new javax.swing.JButton();
        jButton_cancelar = new javax.swing.JButton();
        jLabel_msg_telefone = new javax.swing.JLabel();
        jLabel_msg_cpf = new javax.swing.JLabel();
        jLabel_msg_nome = new javax.swing.JLabel();
        jLabel_msg_dt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SisCardio :: Atualizar Dados de Paciente");
        setAlwaysOnTop(true);

        jLabel_topo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_topo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sign-up48x48.png"))); // NOI18N
        jLabel_topo.setText("Editar Cadastro de Paciente");
        jLabel_topo.setBounds(90, 30, 500, 42);
        jDesktopPaneGeral.add(jLabel_topo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel_nome.setLabelFor(jTextField_nome);
        jLabel_nome.setText("Nome:");
        jLabel_nome.setBounds(100, 87, 120, 40);
        jDesktopPaneGeral.add(jLabel_nome, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTextField_nome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_nomeFocusLost(evt);
            }
        });
        jTextField_nome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_nomeKeyReleased(evt);
            }
        });
        jTextField_nome.setBounds(280, 80, 470, 40);
        jDesktopPaneGeral.add(jTextField_nome, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel_dt_nascimento.setLabelFor(jFormattedTextField_dt_nascimento);
        jLabel_dt_nascimento.setText("Data de nascimento:");
        jLabel_dt_nascimento.setBounds(100, 137, 190, 40);
        jDesktopPaneGeral.add(jLabel_dt_nascimento, javax.swing.JLayeredPane.DEFAULT_LAYER);

        try {
            jFormattedTextField_dt_nascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextField_dt_nascimento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jFormattedTextField_dt_nascimentoFocusLost(evt);
            }
        });
        jFormattedTextField_dt_nascimento.setBounds(280, 130, 180, 40);
        jDesktopPaneGeral.add(jFormattedTextField_dt_nascimento, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel_cpf.setLabelFor(jFormattedTextField_cpf);
        jLabel_cpf.setText("Cpf:");
        jLabel_cpf.setBounds(100, 190, 150, 50);
        jDesktopPaneGeral.add(jLabel_cpf, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jFormattedTextField_cpf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jFormattedTextField_cpfFocusLost(evt);
            }
        });
        jFormattedTextField_cpf.setBounds(280, 190, 220, 50);
        jDesktopPaneGeral.add(jFormattedTextField_cpf, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel_sexo.setLabelFor(jComboBox_sexo);
        jLabel_sexo.setText("Sexo:");
        jLabel_sexo.setBounds(100, 260, 150, 50);
        jDesktopPaneGeral.add(jLabel_sexo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jComboBox_sexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Feminino", "Masculino" }));
        jComboBox_sexo.setBounds(280, 260, 170, 50);
        jDesktopPaneGeral.add(jComboBox_sexo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel_telefone.setLabelFor(jFormattedTextField_telefone);
        jLabel_telefone.setText("Telefone:");
        jLabel_telefone.setBounds(100, 340, 140, 40);
        jDesktopPaneGeral.add(jLabel_telefone, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jFormattedTextField_telefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField_telefoneActionPerformed(evt);
            }
        });
        jFormattedTextField_telefone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jFormattedTextField_telefoneKeyReleased(evt);
            }
        });
        jFormattedTextField_telefone.setBounds(280, 340, 180, 40);
        jDesktopPaneGeral.add(jFormattedTextField_telefone, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton_atualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/document-save22x22.png"))); // NOI18N
        jButton_atualizar.setMnemonic('a');
        jButton_atualizar.setText("Atualizar");
        jButton_atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_atualizarActionPerformed(evt);
            }
        });
        jButton_atualizar.setBounds(280, 430, 160, 50);
        jDesktopPaneGeral.add(jButton_atualizar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancel.png"))); // NOI18N
        jButton_cancelar.setMnemonic('c');
        jButton_cancelar.setText("Cancelar");
        jButton_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cancelarActionPerformed(evt);
            }
        });
        jButton_cancelar.setBounds(620, 430, 140, 50);
        jDesktopPaneGeral.add(jButton_cancelar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel_msg_telefone.setForeground(new java.awt.Color(250, 0, 0));
        jLabel_msg_telefone.setBounds(490, 340, 190, 40);
        jDesktopPaneGeral.add(jLabel_msg_telefone, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel_msg_cpf.setForeground(new java.awt.Color(250, 0, 0));
        jLabel_msg_cpf.setBounds(510, 190, 150, 50);
        jDesktopPaneGeral.add(jLabel_msg_cpf, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel_msg_nome.setForeground(new java.awt.Color(250, 0, 0));
        jLabel_msg_nome.setBounds(770, 80, 250, 40);
        jDesktopPaneGeral.add(jLabel_msg_nome, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel_msg_dt.setForeground(new java.awt.Color(250, 0, 0));
        jLabel_msg_dt.setBounds(470, 130, 220, 40);
        jDesktopPaneGeral.add(jLabel_msg_dt, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPaneGeral, javax.swing.GroupLayout.DEFAULT_SIZE, 1296, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jDesktopPaneGeral, javax.swing.GroupLayout.DEFAULT_SIZE, 835, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cancelarActionPerformed
        this.setAlwaysOnTop(false);
        new exibirPaciente().setVisible(true);
        this.dispose();
       
    }//GEN-LAST:event_jButton_cancelarActionPerformed

    private void jButton_atualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_atualizarActionPerformed
        String nome = jTextField_nome.getText();
        String dataNascimento = jFormattedTextField_dt_nascimento.getText();
        String cpf = jFormattedTextField_cpf.getText();
        String telefone = jFormattedTextField_telefone.getText();
        String sexo = jComboBox_sexo.getSelectedItem().toString();
        
        this.setAlwaysOnTop(false);
        
        if(nome.trim().equals("") || dataNascimento.trim().equals("") || cpf.trim().equals("") || telefone.trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Todos os campos são obrigatório. Preenchá-los.", "Alerta do Sistema",JOptionPane.WARNING_MESSAGE);
        }
        else{
            Fachada f = new Fachada();
            Paciente p = new Paciente(this.p.getId(),nome, dataNascimento, cpf, sexo,telefone);
            try {
                f.editarPaciente(p);
                jButton_cancelar.setText("Voltar");
              
            } catch (PacienteErro ex) {
                Logger.getLogger(editaCadastroPaciente.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
        
    }//GEN-LAST:event_jButton_atualizarActionPerformed

    private void jFormattedTextField_cpfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFormattedTextField_cpfFocusLost
        String t = jFormattedTextField_cpf.getText().replace(".","").replace("-","").trim();
        this.cpfValido = (t.length() == 11);
        if(this.cpfValido && base.validaCPF(t)){
            jLabel_msg_cpf.setIcon(null);
            jLabel_msg_cpf.setText("");
        } 
        else {
            jLabel_msg_cpf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/nook16x16.png")));
            jLabel_msg_cpf.setText("CPF inválido");
        }
        jButton_atualizar.setEnabled(this.camposValidos());
        
        this.setAlwaysOnTop(false);
        
    }//GEN-LAST:event_jFormattedTextField_cpfFocusLost

    private void jFormattedTextField_telefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField_telefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField_telefoneActionPerformed

    private void jTextField_nomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_nomeKeyReleased
        String t = base.getTexto(jTextField_nome.getText());
        jTextField_nome.setText(t);
        this.nomeValido = !t.equals("");
        jButton_atualizar.setEnabled(this.camposValidos());    
    }//GEN-LAST:event_jTextField_nomeKeyReleased

    private void jFormattedTextField_telefoneKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextField_telefoneKeyReleased
        this.telefoneValido = (jFormattedTextField_telefone.getText().replace("(","").replace(")","").replace("-","").trim().length() == 11);
        if(this.telefoneValido){
            jLabel_msg_telefone.setIcon(null);
            jLabel_msg_telefone.setText("");
        } 
        else {
            jLabel_msg_telefone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/noOk16x16.png")));
            jLabel_msg_telefone.setText("Telefone inválido");
        }
        jButton_atualizar.setEnabled(this.camposValidos());  
    }//GEN-LAST:event_jFormattedTextField_telefoneKeyReleased

    private void jTextField_nomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_nomeFocusLost
        ExpressaoRegular er =  new ExpressaoRegular();
        this.nomeValido = er.isTexto(jTextField_nome.getText());
        if(this.nomeValido){
            jLabel_msg_nome.setIcon(null);
            jLabel_msg_nome.setText("");
        } 
        else {
            jLabel_msg_nome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/nook16x16.png")));
            jLabel_msg_nome.setText("Campo alfabetico");
            jTextField_nome.setText("");
        }
        jButton_atualizar.setEnabled(this.camposValidos());
    }//GEN-LAST:event_jTextField_nomeFocusLost

    private void jFormattedTextField_dt_nascimentoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFormattedTextField_dt_nascimentoFocusLost
        Data dt = new Data();
        String nascimento = jFormattedTextField_dt_nascimento.getText();
        this.dataValida = dt.isDataValida(nascimento);
        if(this.dataValida){
            GregorianCalendar calendar = new GregorianCalendar();  
            int year = calendar.get(GregorianCalendar.YEAR);
            int month = calendar.get(GregorianCalendar.MONTH) + 1;
            int day = calendar.get(GregorianCalendar.DAY_OF_MONTH);
            
            String a = jFormattedTextField_dt_nascimento.getText().substring(6,nascimento.trim().length());
            String d = (String) jFormattedTextField_dt_nascimento.getText().subSequence(0,2);
            String m = (String) jFormattedTextField_dt_nascimento.getText().subSequence(3,5);
            
            int ano = Integer.parseInt(a);
            int mes = Integer.parseInt(m);
            int dia = Integer.parseInt(d);
            
            if(year > ano && ano > (year-200)){
                jLabel_msg_dt.setIcon(null);
                jLabel_msg_dt.setText("");
            }else if(year == ano){
               
                if(month < mes){
                    jLabel_msg_dt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/nook16x16.png")));
                    jLabel_msg_dt.setText("Data inválido");
                    this.dataValida = false;
                }else if(month == mes && day < dia){
                    jLabel_msg_dt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/nook16x16.png")));
                    jLabel_msg_dt.setText("Data inválido");
                    this.dataValida = false;
                }
               
            }else{
                jLabel_msg_dt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/nook16x16.png")));
                jLabel_msg_dt.setText("Data inválido");
                this.dataValida = false;
            }
        } 
        else {
            jLabel_msg_dt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/nook16x16.png")));
            jLabel_msg_dt.setText("Data inválida");
        }
        jButton_atualizar.setEnabled(this.camposValidos());
    }//GEN-LAST:event_jFormattedTextField_dt_nascimentoFocusLost
    
    private boolean camposValidos(){
        return this.nomeValido && this.dataValida && telefoneValido;
    }
    
    private Base base = new Base();
    private boolean nomeValido = true, dataValida = true, cpfValido = true, telefoneValido = true; 
    private Paciente p;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_atualizar;
    private javax.swing.JButton jButton_cancelar;
    private javax.swing.JComboBox jComboBox_sexo;
    private javax.swing.JDesktopPane jDesktopPaneGeral;
    private javax.swing.JFormattedTextField jFormattedTextField_cpf;
    private javax.swing.JFormattedTextField jFormattedTextField_dt_nascimento;
    private javax.swing.JFormattedTextField jFormattedTextField_telefone;
    private javax.swing.JLabel jLabel_cpf;
    private javax.swing.JLabel jLabel_dt_nascimento;
    private javax.swing.JLabel jLabel_msg_cpf;
    private javax.swing.JLabel jLabel_msg_dt;
    private javax.swing.JLabel jLabel_msg_nome;
    private javax.swing.JLabel jLabel_msg_telefone;
    private javax.swing.JLabel jLabel_nome;
    private javax.swing.JLabel jLabel_sexo;
    private javax.swing.JLabel jLabel_telefone;
    private javax.swing.JLabel jLabel_topo;
    private javax.swing.JTextField jTextField_nome;
    // End of variables declaration//GEN-END:variables
}
