/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import fachada.Fachada;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.Iterator;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import laudo.*;
import laudoEscore.LaudoEscoreErro;
import laudoEstresse.LaudoEstresse;
import laudoEstresse.LaudoEstresseErro;
import paciente.*;

/**
 *
 * @author arlindo
 */
public class exibirLaudo extends javax.swing.JFrame {
    
    DefaultTableModel modelo;
    Paciente paciente;
    /**
     * Creates new form exibirLaudo
     */
    public exibirLaudo(Paciente paciente){
        
        this.setAlwaysOnTop(true);
       
        initComponents();
        this.paciente = paciente;
        try {
            atualizarLista(paciente.getId());
        } catch (LaudoErro ex) {
            Logger.getLogger(exibirLaudo.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        Dimension d = new Dimension (  
            (int) Toolkit.getDefaultToolkit ().getScreenSize ().getWidth (),(int) Toolkit.getDefaultToolkit().getScreenSize().getHeight());  

        this.setSize(d);
        
        System.out.println(d.height); 
        System.out.println(d.width); 
        
        this.setPreferredSize(d);
    }
    
    private void atualizarLista(int pacienteId) throws LaudoErro{
        
        this.setAlwaysOnTop(false);
        
        String [] colunas = new String []{"Código","Data"};
        modelo = new DefaultTableModel(null, colunas){
            
        @Override
        public boolean isCellEditable(int row, int col){
                return false;
            }
        };
        
        Fachada f = new Fachada();
        List listar = f.listarLaudo(pacienteId);
        if(listar.isEmpty()){
            jButton_editar.setVisible(false);
            
        }
        
        Iterator it = listar.iterator();
        while(it.hasNext()){
            Laudo l = (Laudo)it.next();
            modelo.addRow(new Object[]{l.getId(),l.getData_criacao()});
        }
        
        jTable_laudo.setModel(modelo);
        jTable_laudo.setShowHorizontalLines(false);
        jTable_laudo.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        jTable_laudo.getColumnModel().getColumn(0).setPreferredWidth(80);   
        jTable_laudo.getColumnModel().getColumn(1).setPreferredWidth(120);  
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane = new javax.swing.JDesktopPane();
        jScrollPane = new javax.swing.JScrollPane();
        jTable_laudo = new javax.swing.JTable();
        jButton_eco = new javax.swing.JButton();
        jButton_editar = new javax.swing.JButton();
        jButton_voltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SisCardio :: Visualizar Laudo");
        setAlwaysOnTop(true);

        jTable_laudo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane.setViewportView(jTable_laudo);

        jScrollPane.setBounds(20, 10, 730, 590);
        jDesktopPane.add(jScrollPane, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton_eco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sign-up32x32.png"))); // NOI18N
        jButton_eco.setMnemonic('e');
        jButton_eco.setText("Emitir Laudo");
        jButton_eco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ecoActionPerformed(evt);
            }
        });
        jButton_eco.setBounds(20, 620, 160, 50);
        jDesktopPane.add(jButton_eco, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton_editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/editar.png"))); // NOI18N
        jButton_editar.setMnemonic('d');
        jButton_editar.setText("Editar Laudo");
        jButton_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_editarActionPerformed(evt);
            }
        });
        jButton_editar.setBounds(190, 620, 160, 50);
        jDesktopPane.add(jButton_editar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton_voltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/br_prev16x16.png"))); // NOI18N
        jButton_voltar.setMnemonic('v');
        jButton_voltar.setText("Voltar");
        jButton_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_voltarActionPerformed(evt);
            }
        });
        jButton_voltar.setBounds(630, 620, 120, 50);
        jDesktopPane.add(jButton_voltar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1230, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, 835, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_ecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ecoActionPerformed
        this.setAlwaysOnTop(false);
        new cadastroLaudo(this.paciente, this).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton_ecoActionPerformed

    private void jButton_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_voltarActionPerformed
        this.setAlwaysOnTop(false);
        this.dispose();
    }//GEN-LAST:event_jButton_voltarActionPerformed

    private void jButton_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_editarActionPerformed
        try {
            Fachada f = new Fachada();
            
            int numLinhaSelecionada = jTable_laudo.getSelectedRow();
            int id = Integer.parseInt(jTable_laudo.getValueAt(numLinhaSelecionada, 0).toString());

            Eco e = f.pesquisarLaudoPorId(id,"sub");
            if(e.getPaciente() != null || e.getId_paciente() != 0){
                this.setAlwaysOnTop(false);
                new editaCadastroSubjetivo(e, this).setVisible(true);
            }
            else {
               e = f.pesquisarLaudoEcoPorId(id);
              if(e.getPaciente() != null || e.getId_paciente() != 0){
                  this.setAlwaysOnTop(false);
                   new editarCadastroLaudoEco(e, this).setVisible(true);
              }
            }
           
         } catch (Exception ex) {
              this.setAlwaysOnTop(false);
              JOptionPane.showMessageDialog(this,"Selecione o Laudo.");
        }
            
        
    }//GEN-LAST:event_jButton_editarActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_eco;
    private javax.swing.JButton jButton_editar;
    private javax.swing.JButton jButton_voltar;
    private javax.swing.JDesktopPane jDesktopPane;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JTable jTable_laudo;
    // End of variables declaration//GEN-END:variables
}