/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import fachada.Fachada;
import java.util.Iterator;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import convenio.*;
import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author arlindo
 */
public class exibirConvenio extends javax.swing.JFrame {

    DefaultTableModel modelo;
    /**
     * Creates new form buscaPaciente
     */
    public exibirConvenio(){
        this.setAlwaysOnTop(true);
        initComponents();
        
         Dimension d = new Dimension (  
            (int) Toolkit.getDefaultToolkit ().getScreenSize ().getWidth (),(int) Toolkit.getDefaultToolkit().getScreenSize().getHeight());  

        this.setSize(d);
        
        System.out.println(d.height); 
        System.out.println(d.width); 
        
        
        
        this.setPreferredSize(d);
        this.setMinimumSize(d);
       
        try {
            atualizarLista("");
        } catch (ConvenioErro ex) {
            Logger.getLogger(exibirConvenio.class.getName()).log(Level.SEVERE, null, ex);
        }
        jTextField_pesquisa.requestFocus();
    }

    /**
     * 
     * @param pesquisa => Valor digitado
     * @throws PacienteErro 
     * 
     */
    public void atualizarLista(String pesquisa) throws ConvenioErro{
        
        this.setAlwaysOnTop(false);
        
        String [] colunas = new String []{"Id do Convenio","Nome", "Status"};
        modelo = new DefaultTableModel(null, colunas){
            
        @Override
        public boolean isCellEditable(int row, int col){
                return false;
            }
        };
        Fachada f = new Fachada();
        List listar = f.pesquisarConvenioPorNomes(pesquisa);
        Iterator it = listar.iterator();
        while(it.hasNext()){
            Convenio c = (Convenio)it.next();
            modelo.addRow(new Object[]{c.getId(),c.getNome(),c.getStatus()});
        }
        
        jTable_pesquisado.setModel(modelo);
        jTable_pesquisado.setShowHorizontalLines(false);
        jTable_pesquisado.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        /* Editado largura das Colunas
         * 0 - Id
         * 1 - Nome
         * 2 - Status
         */
        jTable_pesquisado.getColumnModel().getColumn(0).setPreferredWidth(80);   
        jTable_pesquisado.getColumnModel().getColumn(1).setPreferredWidth(120);  
        jTable_pesquisado.getColumnModel().getColumn(2).setPreferredWidth(100);
        
        
    }
       
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane_Geral = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jTextField_pesquisa = new javax.swing.JTextField();
        jScrollPane_tabela = new javax.swing.JScrollPane();
        jTable_pesquisado = new javax.swing.JTable();
        jButton_voltar = new javax.swing.JButton();
        jButton_editar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SisCardio :: Visualizar Convênio");
        setAlwaysOnTop(true);
        setName("frame_exibir"); // NOI18N
        setResizable(false);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/find16x16.png"))); // NOI18N
        jLabel1.setText("Buscar");
        jLabel1.setBounds(20, 20, 620, 40);
        jDesktopPane_Geral.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTextField_pesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_pesquisaActionPerformed(evt);
            }
        });
        jTextField_pesquisa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_pesquisaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_pesquisaFocusLost(evt);
            }
        });
        jTextField_pesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_pesquisaKeyReleased(evt);
            }
        });
        jTextField_pesquisa.setBounds(20, 60, 500, 20);
        jDesktopPane_Geral.add(jTextField_pesquisa, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTable_pesquisado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane_tabela.setViewportView(jTable_pesquisado);

        jScrollPane_tabela.setBounds(20, 100, 740, 430);
        jDesktopPane_Geral.add(jScrollPane_tabela, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton_voltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/br_prev16x16.png"))); // NOI18N
        jButton_voltar.setMnemonic('v');
        jButton_voltar.setText("Voltar");
        jButton_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_voltarActionPerformed(evt);
            }
        });
        jButton_voltar.setBounds(630, 550, 120, 50);
        jDesktopPane_Geral.add(jButton_voltar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton_editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/edit.png"))); // NOI18N
        jButton_editar.setMnemonic('e');
        jButton_editar.setText("Editar");
        jButton_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_editarActionPerformed(evt);
            }
        });
        jButton_editar.setBounds(20, 550, 120, 50);
        jDesktopPane_Geral.add(jButton_editar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane_Geral, javax.swing.GroupLayout.PREFERRED_SIZE, 1372, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane_Geral, javax.swing.GroupLayout.DEFAULT_SIZE, 766, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_pesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_pesquisaKeyReleased
        String filtro = jTextField_pesquisa.getText();
        try {
            atualizarLista(filtro);
        } catch (ConvenioErro ex) {
            Logger.getLogger(exibirConvenio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jTextField_pesquisaKeyReleased

    private void jTextField_pesquisaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_pesquisaFocusLost
        String pesquisado = jTextField_pesquisa.getText();
        if(pesquisado.equals("")){
            jTextField_pesquisa.setText("Digite o nome do Convenio");
        }
    }//GEN-LAST:event_jTextField_pesquisaFocusLost

    private void jTextField_pesquisaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_pesquisaFocusGained
       jTextField_pesquisa.setText("");
    }//GEN-LAST:event_jTextField_pesquisaFocusGained

    private void jButton_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_voltarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton_voltarActionPerformed

    private void jButton_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_editarActionPerformed
        try {
            
            int numLinhaSelecionada = jTable_pesquisado.getSelectedRow();
         
            int id = Integer.parseInt(jTable_pesquisado.getValueAt(numLinhaSelecionada, 0).toString());
            String nome = jTable_pesquisado.getValueAt(numLinhaSelecionada, 1).toString();
            String status = jTable_pesquisado.getValueAt(numLinhaSelecionada, 2).toString();
            
            
           
            
            Convenio c = new Convenio(id,nome,status);
            new editaConvenio(c).setVisible(true);
        
        } catch (Exception e){
            System.out.print("Não selecionado. ");
        }
    }//GEN-LAST:event_jButton_editarActionPerformed

    private void jTextField_pesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_pesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_pesquisaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_editar;
    private javax.swing.JButton jButton_voltar;
    private javax.swing.JDesktopPane jDesktopPane_Geral;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane_tabela;
    private javax.swing.JTable jTable_pesquisado;
    private javax.swing.JTextField jTextField_pesquisa;
    // End of variables declaration//GEN-END:variables
}
