/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import fachada.Fachada;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.Iterator;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import paciente.*;

/**
 *
 * @author arlindo
 */
public class exibirPaciente extends javax.swing.JFrame {

    DefaultTableModel modelo;
    /**
     * Creates new form buscaPaciente
     */
    public exibirPaciente(){
        
       initComponents();
        try {
            atualizarLista("");
        } catch (PacienteErro ex) {
            this.setAlwaysOnTop(false);
            Logger.getLogger(exibirPaciente.class.getName()).log(Level.SEVERE, null, ex);
        }
         this.setAlwaysOnTop(true);
        
        Dimension d = new Dimension (  
            (int) Toolkit.getDefaultToolkit ().getScreenSize ().getWidth (),(int) Toolkit.getDefaultToolkit().getScreenSize().getHeight());  

        this.setSize(d);
        
        System.out.println(d.height); 
        System.out.println(d.width); 
        
        this.setPreferredSize(d);
        jTextField_pesquisa.requestFocus();
        
        
         
    }

    /**
     * 
     * @param pesquisa => Valor digitado
     * @throws PacienteErro 
     * 
     */
    public void atualizarLista(String pesquisa) throws PacienteErro{
        
        this.setAlwaysOnTop(false);
        
        String [] colunas = new String []{"Id do Paciente","Nome", "Data de Nascimento", "CPF", "Sexo","Telefone"};
        modelo = new DefaultTableModel(null, colunas){
            
        @Override
        public boolean isCellEditable(int row, int col){
                return false;
            }
        };
        Fachada f = new Fachada();
        List listar = f.listarPaciente(pesquisa);
        Iterator it = listar.iterator();
        while(it.hasNext()){
            Paciente p = (Paciente)it.next();
            modelo.addRow(new Object[]{p.getId(),p.getNome(),p.getDataNasc(),p.getCpf(),p.getSexo(),p.getTel()});
        }
        
        jTable_pesquisado.setModel(modelo);
        jTable_pesquisado.setShowHorizontalLines(false);
        jTable_pesquisado.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        /* Editado largura das Colunas
         * 0 - Id
         * 1 - Nome
         * 2 - Data de nascimento
         * 3 - Cpf
         * 4 - Sexo
         * 5 - Telefone
         */
        jTable_pesquisado.getColumnModel().getColumn(0).setPreferredWidth(80);   
        jTable_pesquisado.getColumnModel().getColumn(1).setPreferredWidth(120);  
        jTable_pesquisado.getColumnModel().getColumn(2).setPreferredWidth(100);
        jTable_pesquisado.getColumnModel().getColumn(4).setPreferredWidth(40);
        jTable_pesquisado.getColumnModel().getColumn(5).setPreferredWidth(60);
        
    }
       
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jDesktopPane_Geral = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jTextField_pesquisa = new javax.swing.JTextField();
        jScrollPane_tabela = new javax.swing.JScrollPane();
        jTable_pesquisado = new javax.swing.JTable();
        jButton_voltar = new javax.swing.JButton();
        jButton_incluir_laudo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SisCardio :: Visualizar Paciente");
        setAlwaysOnTop(true);
        setName("frame_exibir"); // NOI18N
        setResizable(false);

        jLabel1.setBackground(new java.awt.Color(250, 250, 250));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/find16x16.png"))); // NOI18N
        jLabel1.setText("Buscar");
        jLabel1.setBounds(20, 10, 140, 40);
        jDesktopPane_Geral.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTextField_pesquisa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_pesquisaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_pesquisaFocusLost(evt);
            }
        });
        jTextField_pesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_pesquisaKeyReleased(evt);
            }
        });
        jTextField_pesquisa.setBounds(20, 50, 500, 30);
        jDesktopPane_Geral.add(jTextField_pesquisa, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTable_pesquisado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane_tabela.setViewportView(jTable_pesquisado);

        jScrollPane_tabela.setBounds(20, 100, 740, 470);
        jDesktopPane_Geral.add(jScrollPane_tabela, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton_voltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/br_prev16x16.png"))); // NOI18N
        jButton_voltar.setMnemonic('v');
        jButton_voltar.setText("Voltar");
        jButton_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_voltarActionPerformed(evt);
            }
        });
        jButton_voltar.setBounds(640, 580, 120, 50);
        jDesktopPane_Geral.add(jButton_voltar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton_incluir_laudo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/doc_lines16x16.png"))); // NOI18N
        jButton_incluir_laudo.setMnemonic('l');
        jButton_incluir_laudo.setText("Laudos");
        jButton_incluir_laudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_incluir_laudoActionPerformed(evt);
            }
        });
        jButton_incluir_laudo.setBounds(20, 580, 120, 50);
        jDesktopPane_Geral.add(jButton_incluir_laudo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jDesktopPane_Geral, javax.swing.GroupLayout.PREFERRED_SIZE, 1358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane_Geral, javax.swing.GroupLayout.PREFERRED_SIZE, 707, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_pesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_pesquisaKeyReleased
        String filtro = jTextField_pesquisa.getText();
        try {
            atualizarLista(filtro);
        } catch (PacienteErro ex) {
            this.setAlwaysOnTop(false);
            Logger.getLogger(exibirPaciente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jTextField_pesquisaKeyReleased

    private void jTextField_pesquisaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_pesquisaFocusLost
        String pesquisado = jTextField_pesquisa.getText();
        if(pesquisado.equals("")){
            jTextField_pesquisa.setText("Digite o nome do paciente");
        }
    }//GEN-LAST:event_jTextField_pesquisaFocusLost

    private void jTextField_pesquisaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_pesquisaFocusGained
       jTextField_pesquisa.setText("");
    }//GEN-LAST:event_jTextField_pesquisaFocusGained

    private void jButton_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_voltarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton_voltarActionPerformed

    private void jButton_incluir_laudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_incluir_laudoActionPerformed
        try {
            
            int numLinhaSelecionada = jTable_pesquisado.getSelectedRow();
            int id = Integer.parseInt(jTable_pesquisado.getValueAt(numLinhaSelecionada, 0).toString());
            
            String nome = jTable_pesquisado.getValueAt(numLinhaSelecionada, 1).toString();
            String dataNascimento = jTable_pesquisado.getValueAt(numLinhaSelecionada, 2).toString();
            String cpf = jTable_pesquisado.getValueAt(numLinhaSelecionada, 3).toString();
            String sexo = jTable_pesquisado.getValueAt(numLinhaSelecionada, 4).toString();
            String telefone = jTable_pesquisado.getValueAt(numLinhaSelecionada, 5).toString();
            
            Paciente paciente = new Paciente(id, nome, dataNascimento, cpf, sexo, telefone);
            this.setAlwaysOnTop(false);
            new exibirLaudo(paciente).setVisible(true);
        
        } catch (Exception e){
            this.setAlwaysOnTop(false);
            JOptionPane.showMessageDialog(this,"Selecione o paciente.");
        }
    }//GEN-LAST:event_jButton_incluir_laudoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_incluir_laudo;
    private javax.swing.JButton jButton_voltar;
    private javax.swing.JDesktopPane jDesktopPane_Geral;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane_tabela;
    private javax.swing.JTable jTable_pesquisado;
    private javax.swing.JTextField jTextField_pesquisa;
    // End of variables declaration//GEN-END:variables
}
