/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import fachada.Fachada;
import java.util.Iterator;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import laudoEscore.*;

/**
 *
 * @author arlindo
 */
public class exibirLaudoEscore extends javax.swing.JFrame {

    /**
     * Creates new form exibirLaudoEscore
     */
    int laudoEco_id;
    
    public exibirLaudoEscore(int laudoEco_id) throws LaudoEscoreErro {
        
        this.setAlwaysOnTop(true);
        
        initComponents();
        this.laudoEco_id = laudoEco_id;
        atualizarLista();
    }
    DefaultTableModel modelo;
    
    private void atualizarLista() throws LaudoEscoreErro{
        
        this.setAlwaysOnTop(false);
        
        String [] colunas = new String []{"Código","Código Ecocadiograma"};
        modelo = new DefaultTableModel(null, colunas){
            
        @Override
        public boolean isCellEditable(int row, int col){
                return false;
            }
        };
        
        Fachada f = new Fachada();
        List listar = f.listarLaudoEscoreByLaudoEcoID(laudoEco_id);
        
        Iterator it = listar.iterator();
        while(it.hasNext()){
            LaudoEscore l = (LaudoEscore)it.next();
            modelo.addRow(new Object[]{l.getId(),l.getLaudoEcoId()});
        }
        
        jTable_escore.setModel(modelo);
        jTable_escore.setShowHorizontalLines(false);
        jTable_escore.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        jTable_escore.getColumnModel().getColumn(0).setPreferredWidth(80);   
        jTable_escore.getColumnModel().getColumn(1).setPreferredWidth(120);  
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jScrollPane = new javax.swing.JScrollPane();
        jTable_escore = new javax.swing.JTable();
        jButton_incluir = new javax.swing.JButton();
        jButton_visualizar = new javax.swing.JButton();
        jButton_voltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SisCardio :: Visualizar Laudo Escore");
        setAlwaysOnTop(true);

        jTable_escore.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane.setViewportView(jTable_escore);

        jScrollPane.setBounds(0, 0, 660, 320);
        jDesktopPane1.add(jScrollPane, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton_incluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Add.png"))); // NOI18N
        jButton_incluir.setMnemonic('i');
        jButton_incluir.setText("Incluir");
        jButton_incluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_incluirActionPerformed(evt);
            }
        });
        jButton_incluir.setBounds(20, 350, 120, 50);
        jDesktopPane1.add(jButton_incluir, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton_visualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Search.png"))); // NOI18N
        jButton_visualizar.setMnemonic('s');
        jButton_visualizar.setText("Visualizar");
        jButton_visualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_visualizarActionPerformed(evt);
            }
        });
        jButton_visualizar.setBounds(150, 350, 120, 50);
        jDesktopPane1.add(jButton_visualizar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton_voltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/br_prev16x16.png"))); // NOI18N
        jButton_voltar.setMnemonic('v');
        jButton_voltar.setText("Voltar");
        jButton_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_voltarActionPerformed(evt);
            }
        });
        jButton_voltar.setBounds(520, 350, 120, 50);
        jDesktopPane1.add(jButton_voltar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 655, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_incluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_incluirActionPerformed
        new cadastroEscore(laudoEco_id).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton_incluirActionPerformed

    private void jButton_visualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_visualizarActionPerformed
  
     try{   
        int numLinhaSelecionada = jTable_escore.getSelectedRow();
        int id = Integer.parseInt(jTable_escore.getValueAt(numLinhaSelecionada, 0).toString());
        
        Fachada f = new Fachada();
        LaudoEscore escore = f.getLaudoEscoreById(id);
        //new editarEscore(escore,laudoEco_id).setVisible(true);
        this.dispose();
      } catch (Exception ex) {
              this.setAlwaysOnTop(false);
            JOptionPane.showMessageDialog(this,"Selecione o Laudo."); 
      }
    }//GEN-LAST:event_jButton_visualizarActionPerformed

    private void jButton_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_voltarActionPerformed
       this.dispose();
    }//GEN-LAST:event_jButton_voltarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_incluir;
    private javax.swing.JButton jButton_visualizar;
    private javax.swing.JButton jButton_voltar;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JTable jTable_escore;
    // End of variables declaration//GEN-END:variables
}
