/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Locale;
import java.util.SimpleTimeZone;
import java.util.TimeZone;

/**
 *
 * 
 */
public class principal extends javax.swing.JFrame {

    /**
     * Creates new form principal
     */
    public principal() {
       
        setExtendedState(MAXIMIZED_BOTH);  
        
        Dimension d = new Dimension (  
            (int) Toolkit.getDefaultToolkit ().getScreenSize ().getWidth (),(int) Toolkit.getDefaultToolkit().getScreenSize().getHeight());  

        this.setSize(d);
        
        System.out.println(d.height); 
        System.out.println(d.width); 
        
        this.setPreferredSize(d);
        this.setMinimumSize(d);
        
        initComponents();
        
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_background = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu_paciente = new javax.swing.JMenu();
        jMenuItem_add_paciente = new javax.swing.JMenuItem();
        jMenuItem_exibir_paciente = new javax.swing.JMenuItem();
        jMenu_medico = new javax.swing.JMenu();
        jMenuItem_add_medico = new javax.swing.JMenuItem();
        Exibir_medico = new javax.swing.JMenuItem();
        jMenu_convenio = new javax.swing.JMenu();
        jMenuItem_cadastrar_convenio = new javax.swing.JMenuItem();
        jMenuItem_buscar_convenio = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem_cadastrarModelo = new javax.swing.JMenuItem();
        jMenuItem_EmitirLaudo = new javax.swing.JMenuItem();
        jMenu_fechar = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SisCardio :: ");
        setFocusableWindowState(false);
        setName("principal"); // NOI18N

        jLabel_background.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logonovo.png"))); // NOI18N
        jLabel_background.setMaximumSize(new java.awt.Dimension(800, 600));
        jLabel_background.setMinimumSize(new java.awt.Dimension(800, 600));

        jMenuBar1.setBackground(new java.awt.Color(250, 250, 250));

        jMenu_paciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/paciente.png"))); // NOI18N
        jMenu_paciente.setMnemonic('p');
        jMenu_paciente.setText("Pacientes");
        jMenu_paciente.setToolTipText("");

        jMenuItem_add_paciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/list_add_user22x22.png"))); // NOI18N
        jMenuItem_add_paciente.setMnemonic('a');
        jMenuItem_add_paciente.setText("Cadastrar Paciente");
        jMenuItem_add_paciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_add_pacienteActionPerformed(evt);
            }
        });
        jMenu_paciente.add(jMenuItem_add_paciente);

        jMenuItem_exibir_paciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/find16x16.png"))); // NOI18N
        jMenuItem_exibir_paciente.setMnemonic('b');
        jMenuItem_exibir_paciente.setText("Buscar Paciente");
        jMenuItem_exibir_paciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_exibir_pacienteActionPerformed(evt);
            }
        });
        jMenu_paciente.add(jMenuItem_exibir_paciente);

        jMenuBar1.add(jMenu_paciente);

        jMenu_medico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/doctor_assistant.png"))); // NOI18N
        jMenu_medico.setMnemonic('m');
        jMenu_medico.setText("Medicos");

        jMenuItem_add_medico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/list_add_user22x22.png"))); // NOI18N
        jMenuItem_add_medico.setText("Cadastrar Medico");
        jMenuItem_add_medico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_add_medicoActionPerformed(evt);
            }
        });
        jMenu_medico.add(jMenuItem_add_medico);

        Exibir_medico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/find16x16.png"))); // NOI18N
        Exibir_medico.setText("Buscar Medico");
        Exibir_medico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Exibir_medicoActionPerformed(evt);
            }
        });
        jMenu_medico.add(Exibir_medico);

        jMenuBar1.add(jMenu_medico);

        jMenu_convenio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/doc_lines32x32.png"))); // NOI18N
        jMenu_convenio.setMnemonic('c');
        jMenu_convenio.setText("Convenios");

        jMenuItem_cadastrar_convenio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/add_list.png"))); // NOI18N
        jMenuItem_cadastrar_convenio.setText("Cadastrar Convenio");
        jMenuItem_cadastrar_convenio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_cadastrar_convenioActionPerformed(evt);
            }
        });
        jMenu_convenio.add(jMenuItem_cadastrar_convenio);

        jMenuItem_buscar_convenio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/find16x16.png"))); // NOI18N
        jMenuItem_buscar_convenio.setText("Buscar Convenio");
        jMenuItem_buscar_convenio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_buscar_convenioActionPerformed(evt);
            }
        });
        jMenu_convenio.add(jMenuItem_buscar_convenio);

        jMenuBar1.add(jMenu_convenio);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/blank_document.png"))); // NOI18N
        jMenu1.setMnemonic('l');
        jMenu1.setText("Laudo");

        jMenuItem_cadastrarModelo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/list-add16x16.png"))); // NOI18N
        jMenuItem_cadastrarModelo.setText("Cadastrar Modelo");
        jMenuItem_cadastrarModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_cadastrarModeloActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem_cadastrarModelo);

        jMenuItem_EmitirLaudo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/list_bullets16x16.png"))); // NOI18N
        jMenuItem_EmitirLaudo.setText("Emitir Laudo");
        jMenuItem_EmitirLaudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_EmitirLaudoActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem_EmitirLaudo);

        jMenuBar1.add(jMenu1);

        jMenu_fechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/application_exit.png"))); // NOI18N
        jMenu_fechar.setMnemonic('r');
        jMenu_fechar.setText("Sair");
        jMenu_fechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu_fecharMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu_fechar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_background, javax.swing.GroupLayout.DEFAULT_SIZE, 1210, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_background, javax.swing.GroupLayout.PREFERRED_SIZE, 555, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("SisCardio");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem_add_pacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_add_pacienteActionPerformed
        new cadastroPaciente().setVisible(true);
    }//GEN-LAST:event_jMenuItem_add_pacienteActionPerformed

    private void jMenuItem_add_medicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_add_medicoActionPerformed
         new cadastroMedico().setVisible(true);
    }//GEN-LAST:event_jMenuItem_add_medicoActionPerformed

    private void jMenuItem_cadastrar_convenioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_cadastrar_convenioActionPerformed
         new cadastroConvenio().setVisible(true);
    }//GEN-LAST:event_jMenuItem_cadastrar_convenioActionPerformed

    private void jMenuItem_exibir_pacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_exibir_pacienteActionPerformed
        new exibirPaciente_atendente().setVisible(true);
    }//GEN-LAST:event_jMenuItem_exibir_pacienteActionPerformed

    private void Exibir_medicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Exibir_medicoActionPerformed
        
        new exibirMedico().setVisible(true);
    }//GEN-LAST:event_Exibir_medicoActionPerformed

    private void jMenuItem_buscar_convenioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_buscar_convenioActionPerformed
        new exibirConvenio().setVisible(true);
    }//GEN-LAST:event_jMenuItem_buscar_convenioActionPerformed

    private void jMenuItem_cadastrarModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_cadastrarModeloActionPerformed
        // TODO add your handling code here:
        new cadastroModelo().setVisible(true);
    }//GEN-LAST:event_jMenuItem_cadastrarModeloActionPerformed

    private void jMenuItem_EmitirLaudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_EmitirLaudoActionPerformed
        // TODO add your handling code here:
        new exibirPaciente().setVisible(true);
    }//GEN-LAST:event_jMenuItem_EmitirLaudoActionPerformed

    private void jMenu_fecharMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu_fecharMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jMenu_fecharMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Exibir_medico;
    private javax.swing.JLabel jLabel_background;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem_EmitirLaudo;
    private javax.swing.JMenuItem jMenuItem_add_medico;
    private javax.swing.JMenuItem jMenuItem_add_paciente;
    private javax.swing.JMenuItem jMenuItem_buscar_convenio;
    private javax.swing.JMenuItem jMenuItem_cadastrarModelo;
    private javax.swing.JMenuItem jMenuItem_cadastrar_convenio;
    private javax.swing.JMenuItem jMenuItem_exibir_paciente;
    private javax.swing.JMenu jMenu_convenio;
    private javax.swing.JMenu jMenu_fechar;
    private javax.swing.JMenu jMenu_medico;
    private javax.swing.JMenu jMenu_paciente;
    // End of variables declaration//GEN-END:variables
}
